### ISSUE TITLE
Не работает с permalinks

### ISSUE THREAD

**Issue by ask0n** [aiiddqd/socialify#1]
Добавлял на страницу через do_shortcode('[btn-hybridauth connect=true provider_id="Vkontakte" text="VK"]'), кнопка появляется при нажатии перенаправление на страницу с ?cp-aa=Vkontakte и все. Ключ от API вбит. Использую permalinks, может быть в нем дело?

**Comment by aiiddqd** [comment]
и все это что? белый экран?
что пишет лог ошибок?

**Comment by ask0n** [comment]
И все - это открывается та же самая страница на которой была нажата кнопка, только с измененным url. Где посмотреть лог ошибок? (в логах вэбсервера ничего нет).

**Comment by aurokk** [comment]
Привет! 

Возможно два варианта почему у Вас не работает плагин, хук "template_redirect" не срабатывает или конструкция "try" вызывает исключение и управление попадает в блок "catch" где нет обработки этого исключения внутри функции "start_session_hybrydauth". 

Так как у меня на нескольких сайтах это работает, то я могу дать Вам только советы как приблизиться к проблеме. 

Попробуйте добавить какой либо вывод внутрь функции "start_session_hybrydauth" в самое начала и в блок "catch" и посмотреть, куда попадает управление и попадает ли. Возможно в Вашем случае нужно заменить хук "template_redirect", если эта функция вообще не срабатывает. 

Если имеется возможность, можете дать мне линк на Ваш сайт я попробую посмотреть что да как еще лично, но попробуйте сделать то, что я посоветовал Вам выше! 

Спасибо!)
